/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spreadoffiresimulation_ver2;

import java.text.DecimalFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Anakan
 */
public class GUI extends javax.swing.JFrame {

    private final Simulator simu;
    private final Fire fire;
    private Forest forest;
    private boolean isAuto = false;
    private static int size = 100; //forest size.
    private static int initTree; 
    private ImageIcon icon;

    /**
     * Creates new form GUI
     * forest is in the default form with size 100%
     * declare fire and simulator class and set location for simulator
     */
    public GUI() {
        forest = new Forest(100);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
        fire = new Fire(forest);
        simu = new Simulator(forest.getSize());
        simu.setLocation(10, 10);
        add(simu);
        delaySetting();
        jPanel4.setVisible(false);
    }
    
    public void delaySetting(){
        delaySlide.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
               delayText.setText("Speed of fire: " +delaySlide.getValue() + " millisec");
               fire.setDelay(delaySlide.getValue());
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        countLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        setbutt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        probBurnText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        setSize = new javax.swing.JComboBox();
        fireprobText = new javax.swing.JTextField();
        densityText = new javax.swing.JTextField();
        help = new javax.swing.JLabel();
        delayText = new javax.swing.JLabel();
        delaySlide = new javax.swing.JSlider();
        startbutt = new javax.swing.JButton();
        resetbutt = new javax.swing.JButton();
        auto = new javax.swing.JRadioButton();
        numTreeLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        percentLeftText = new javax.swing.JLabel();
        percentBurnText = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        detailbutt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spread of Fire Simulator BY Group#12");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(808, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        countLabel.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        countLabel.setForeground(new java.awt.Color(255, 255, 255));
        countLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spreadoffiresimulation_ver2/images/icon.png"))); // NOI18N
        countLabel.setText("STEP COUNT: 0");
        countLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(countLabel);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 3, true), " Setting Your Forest ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 2, 16), new java.awt.Color(255, 153, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("Set density of forest:");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Set Fire Catch:");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setText("Set prob burning: ");

        setbutt.setBackground(new java.awt.Color(153, 153, 255));
        setbutt.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        setbutt.setForeground(new java.awt.Color(255, 255, 255));
        setbutt.setText("Set");
        setbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setbuttActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        probBurnText.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setText("Forest Size: 100 %");

        setSize.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        setSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "large", "big", "medium", "small" }));
        setSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSizeActionPerformed(evt);
            }
        });

        fireprobText.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        densityText.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spreadoffiresimulation_ver2/images/help_page_sign.png"))); // NOI18N
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
        });

        delayText.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        delayText.setText("Speed of Fire: 100 millisec");

        delaySlide.setMajorTickSpacing(100);
        delaySlide.setMaximum(1000);
        delaySlide.setMinimum(10);
        delaySlide.setMinorTickSpacing(50);
        delaySlide.setPaintTicks(true);
        delaySlide.setSnapToTicks(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(densityText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fireprobText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(probBurnText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(setbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(help))
                            .addComponent(delayText)
                            .addComponent(delaySlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(densityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fireprobText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(probBurnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(setSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(delayText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delaySlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(setbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(help, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        startbutt.setBackground(new java.awt.Color(255, 102, 51));
        startbutt.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        startbutt.setForeground(new java.awt.Color(255, 255, 255));
        startbutt.setText("Burn !");
        startbutt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        startbutt.setEnabled(false);
        startbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbuttActionPerformed(evt);
            }
        });

        resetbutt.setBackground(new java.awt.Color(204, 255, 51));
        resetbutt.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        resetbutt.setForeground(new java.awt.Color(255, 255, 255));
        resetbutt.setText("Reset");
        resetbutt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        resetbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttActionPerformed(evt);
            }
        });

        auto.setBackground(new java.awt.Color(0, 153, 153));
        auto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        auto.setForeground(new java.awt.Color(255, 255, 255));
        auto.setText("Auto Burn");
        auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoActionPerformed(evt);
            }
        });

        numTreeLabel.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        numTreeLabel.setForeground(new java.awt.Color(255, 255, 255));
        numTreeLabel.setText("NO. OF TREE LEFT:");

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        percentLeftText.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        percentLeftText.setText("Percent of tree left: ");

        percentBurnText.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        percentBurnText.setText("Percent of tree burned: ");

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spreadoffiresimulation_ver2/images/close.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(percentLeftText)
                    .addComponent(percentBurnText))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(percentLeftText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(percentBurnText, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        detailbutt.setBackground(new java.awt.Color(255, 204, 204));
        detailbutt.setText("...");
        detailbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailbuttActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spreadoffiresimulation_ver2/images/group12icon.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 10)); // NOI18N
        jLabel6.setText("version 1.3.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numTreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(auto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(startbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(resetbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(detailbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(106, 106, 106))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startbutt)
                    .addComponent(resetbutt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(auto, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(numTreeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailbutt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.getAccessibleContext().setAccessibleName(" Setting your forest ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * If the auto radio button is selected, it will set isAuto to be true
     * otherwise, it will remain false.
     * @param evt 
     */
    private void autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoActionPerformed
        isAuto = auto.isSelected();
    }//GEN-LAST:event_autoActionPerformed

    /**
     * reset everything that associate with the simulator panel
     * @param evt 
     */
    private void resetbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttActionPerformed
        fire.resetFire();
        forest = new Forest(size);
        simu.newSimu(forest.getSize());
        initTree = forest.getTree();
        countLabel.setText("STEP COUNT: " + fire.getCount());
        numTreeLabel.setText("NO. OF TREE: " +forest.getTree());
        percentLeftText.setText("percent of tree left: ");
        percentBurnText.setText("percent of tree burned: ");
        startbutt.setEnabled(false);
    }//GEN-LAST:event_resetbuttActionPerformed

    /**
     * start button will work automatically when isAuto is true
     * otherwise, it will work once only if it is pressed
     * 
     * start button invokes the probCatch method from Fire class
     * if isAuto is true
     * otherwise, it will invoke the stepBurn method from Fire class
     * @param evt 
     */
    private void startbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbuttActionPerformed
        final double probFire = Double.parseDouble(fireprobText.getText());
        if (isAuto) {
            Thread t = new Thread(new Runnable() {
                @Override
                public void run() {
                        if(fire.isStop() == false){
                            fire.probCatch(probFire);
                            forest.countTree();
                            countLabel.setText("STEP COUNT: " + fire.getCount());
                            numTreeLabel.setText("NO. OF TREE: " +forest.getTree());
                            
                        }
                        forest.countTree();
                        double result = forest.calculatedTreeLeft(forest.getTree(), initTree);
                        percentLeftText.setText("percent of tree left: " + result
                                    +" %");
                        percentBurnText.setText("percent of tree burned: " + forest.calculatedTreeBurned(result)
                                    + " %");
                }
            });
            t.start();
        } else {
            Thread t = new Thread(new Runnable() {
                @Override
                public void run() {
                    if (fire.isStop() == true) {
                        
                    } else {
                        fire.stepBurn(probFire);
                        forest.countTree();
                        countLabel.setText("STEP COUNT: " + fire.getCount());
                        numTreeLabel.setText("NO. OF TREE: " +forest.getTree());
                        forest.countTree();
                        double result = forest.calculatedTreeLeft(forest.getTree(), initTree);
                        percentLeftText.setText("percent of tree left: " + result
                                    +" %");
                        percentBurnText.setText("percent of tree burned: " + forest.calculatedTreeBurned(result)
                                    + " %");
                    }
                }
            });
            t.start();    
        }
    }//GEN-LAST:event_startbuttActionPerformed

    /**
     * the combo boxes will be selected to set size of the forest
     * @param evt 
     */
    private void setSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSizeActionPerformed
        if(setSize.getModel().getSelectedItem().equals("large")){
            size = 100;
        } else if(setSize.getModel().getSelectedItem().equals("big")){
            size = 50;
        } else if(setSize.getModel().getSelectedItem().equals("medium")){
            size = 20;
        } else {
            size = 10;
        }
        jLabel4.setText("Forest Size: " + size + " %");
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                forest = new Forest(size);
                simu.newSimu(forest.getSize());
            }
        });
        t.start();
    }//GEN-LAST:event_setSizeActionPerformed

    /**
     * reset all the inputs to the default value
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fireprobText.setText("");
        densityText.setText("");
        probBurnText.setText("");
        startbutt.setEnabled(false);
        forest = new Forest(100);
        simu.newSimu(forest.getSize());
        initTree = forest.getTree();
        countLabel.setText("STEP COUNT: 0");
        numTreeLabel.setText("NO. OF TREE: " +forest.getTree());
        jLabel4.setText("Forest Size: 100 %");
        setSize.getModel().setSelectedItem("large");
        percentLeftText.setText("percent of tree left: ");
        percentBurnText.setText("percent of tree burned: ");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * set all inputs in their places
     * the error message will be invoked, if there is any empty input
     * @param evt 
     */
    private void setbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setbuttActionPerformed
        try {
            if(!densityText.getText().contains(".")){
                JOptionPane.showMessageDialog(null,"All the inputs must be 'decimal number' \n"
                        + "and they must be '0-1' values.",
                        "Error 404 : Input(s) incorect", JOptionPane.ERROR_MESSAGE);
            } else {
                double den = Double.parseDouble(densityText.getText());
                double probBurn = Double.parseDouble(probBurnText.getText());
                forest = new Forest(size, den, probBurn);
                simu.newSimu(size);
                initTree = forest.getTree();
                numTreeLabel.setText("NO. OF TREE: " +initTree);
                startbutt.setEnabled(true);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please insert every inputs",
                "Error 404 : Boxes need input", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_setbuttActionPerformed

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        JOptionPane.showMessageDialog(null, 
                        "Every inputs are 0-1. (i.e. if '50%' is equal to '0.5') \n"
                        + "After finished put all the input, click 'set' button.", 
                "Instruction", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_helpMouseClicked

    private void detailbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailbuttActionPerformed
        jPanel4.setVisible(true);
    }//GEN-LAST:event_detailbuttActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jPanel4.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton auto;
    private javax.swing.JLabel countLabel;
    private javax.swing.JSlider delaySlide;
    private javax.swing.JLabel delayText;
    private javax.swing.JTextField densityText;
    private javax.swing.JButton detailbutt;
    private javax.swing.JTextField fireprobText;
    private javax.swing.JLabel help;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel numTreeLabel;
    private javax.swing.JLabel percentBurnText;
    private javax.swing.JLabel percentLeftText;
    private javax.swing.JTextField probBurnText;
    private javax.swing.JButton resetbutt;
    private javax.swing.JComboBox setSize;
    private javax.swing.JButton setbutt;
    private javax.swing.JButton startbutt;
    // End of variables declaration//GEN-END:variables

    /*private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getClass().getResource("icon.png"));
    }*/
}
