/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spreadoffiresimulation_ver2;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Anakan
 */
public class GUI extends javax.swing.JFrame {

    private final Simulator simu;
    private final Fire fire;
    private Forest forest;
    private boolean isAuto = false;
    private static int size = 100; //forest size.

    /**
     * Creates new form GUI
     * forest is in the default form with size 100%
     * declare fire and simulator class and set location for simulator
     */
    public GUI() {
        forest = new Forest(100);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
        fire = new Fire(forest);
        simu = new Simulator(forest.getSize());
        simu.setLocation(10, 10);
        add(simu);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        countLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        setbutt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        probBurnText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        setSize = new javax.swing.JComboBox();
        fireprobText = new javax.swing.JTextField();
        densityText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        startbutt = new javax.swing.JButton();
        resetbutt = new javax.swing.JButton();
        auto = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        numTreeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spread of Fire Simulator BY Group#12");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(820, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.GridLayout());

        countLabel.setBackground(new java.awt.Color(255, 255, 255));
        countLabel.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        countLabel.setForeground(new java.awt.Color(255, 255, 255));
        countLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spreadoffiresimulation_ver2/icon.png"))); // NOI18N
        countLabel.setText("STEP COUNT: 0");
        countLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(countLabel);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 3, true), " Setting Your Forest ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 2, 16), new java.awt.Color(255, 153, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("Set density of forest:");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Set Fire probability:");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setText("Set prob burning: ");

        setbutt.setBackground(new java.awt.Color(153, 153, 255));
        setbutt.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        setbutt.setForeground(new java.awt.Color(255, 255, 255));
        setbutt.setText("Set");
        setbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setbuttActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        probBurnText.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setText("Forest Size: 100 %");

        setSize.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        setSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "large", "big", "medium", "small" }));
        setSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSizeActionPerformed(evt);
            }
        });

        fireprobText.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        densityText.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spreadoffiresimulation_ver2/help_page_sign.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(densityText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fireprobText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(probBurnText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(setbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(densityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fireprobText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(probBurnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(setSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(setbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        startbutt.setBackground(new java.awt.Color(255, 102, 51));
        startbutt.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        startbutt.setForeground(new java.awt.Color(255, 255, 255));
        startbutt.setText("Burn !");
        startbutt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        startbutt.setEnabled(false);
        startbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbuttActionPerformed(evt);
            }
        });

        resetbutt.setBackground(new java.awt.Color(204, 255, 51));
        resetbutt.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        resetbutt.setForeground(new java.awt.Color(255, 255, 255));
        resetbutt.setText("Reset");
        resetbutt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        resetbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttActionPerformed(evt);
            }
        });

        auto.setBackground(new java.awt.Color(0, 153, 153));
        auto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        auto.setForeground(new java.awt.Color(255, 255, 255));
        auto.setText("Auto Burn");
        auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoActionPerformed(evt);
            }
        });

        numTreeLabel.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        numTreeLabel.setForeground(new java.awt.Color(255, 255, 255));
        numTreeLabel.setText("NO. OF TREE LEFT:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(auto)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(startbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numTreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startbutt)
                    .addComponent(resetbutt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(auto, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numTreeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.getAccessibleContext().setAccessibleName(" Setting your forest ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * If the auto radio button is selected, it will set isAuto to be true
     * otherwise, it will remain false.
     * @param evt 
     */
    private void autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoActionPerformed
        isAuto = auto.isSelected();
    }//GEN-LAST:event_autoActionPerformed

    /**
     * reset everything that associate with the simulator panel
     * @param evt 
     */
    private void resetbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttActionPerformed
        fire.resetFire();
        forest = new Forest(size);
        simu.newSimu(forest.getSize());
        countLabel.setText("STEP COUNT: " + fire.getCount());
        numTreeLabel.setText("NO. OF TREE: " +forest.getTree());
        startbutt.setEnabled(false);
    }//GEN-LAST:event_resetbuttActionPerformed

    /**
     * start button will work automatically when isAuto is true
     * otherwise, it will work once only if it is pressed
     * 
     * start button invokes the probCatch method from Fire class
     * if isAuto is true
     * otherwise, it will invoke the stepBurn method from Fire class
     * @param evt 
     */
    private void startbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbuttActionPerformed
        final double probFire = Double.parseDouble(fireprobText.getText());
        if (isAuto) {
            Thread t = new Thread(new Runnable() {
                @Override
                public void run() {
                    if (fire.isStop() == true) {
                        //do noting
                    } else {
                        fire.probCatch(probFire);
                        countLabel.setText("STEP COUNT: " + fire.getCount());
                        numTreeLabel.setText("NO. OF TREE: " +forest.getTree());
                    }
                }
            });
            t.start();
        } else {
            Thread t = new Thread(new Runnable() {
                @Override
                public void run() {
                    if (fire.isStop() == true) {
                        //do nothing
                    } else {
                        fire.stepBurn(probFire);
                        countLabel.setText("STEP COUNT: " + fire.getCount());
                        numTreeLabel.setText("NO. OF TREE: " +forest.getTree());
                    }
                }
            });
            t.start();
        }
    }//GEN-LAST:event_startbuttActionPerformed

    /**
     * the combo boxes will be selected to set size of the forest
     * @param evt 
     */
    private void setSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSizeActionPerformed
        if(setSize.getModel().getSelectedItem().equals("large")){
            size = 100;
        } else if(setSize.getModel().getSelectedItem().equals("big")){
            size = 50;
        } else if(setSize.getModel().getSelectedItem().equals("medium")){
            size = 20;
        } else {
            size = 10;
        }
        jLabel4.setText("Forest Size: " + size + " %");
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                forest = new Forest(size);
                simu.newSimu(forest.getSize());
            }
        });
        t.start();
    }//GEN-LAST:event_setSizeActionPerformed

    /**
     * reset all the inputs to the default value
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fireprobText.setText("");
        densityText.setText("");
        probBurnText.setText("");
        startbutt.setEnabled(false);
        forest = new Forest(100);
        simu.newSimu(forest.getSize());
        countLabel.setText("STEP COUNT: 0");
        numTreeLabel.setText("NO. OF TREE: " +forest.getTree());
        jLabel4.setText("Forest Size: 100 %");
        setSize.getModel().setSelectedItem("large");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * set all inputs in their places
     * the error message will be invoked, if there is any empty input
     * @param evt 
     */
    private void setbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setbuttActionPerformed
        try {
            double den = Double.parseDouble(densityText.getText());
            double probBurn = Double.parseDouble(probBurnText.getText());
            forest = new Forest(size, den, probBurn);
            simu.newSimu(size);
            numTreeLabel.setText("NO. OF TREE: " +forest.getTree());
            startbutt.setEnabled(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please insert every inputs",
                "Error 404 : Boxes need input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_setbuttActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        JOptionPane.showMessageDialog(null, 
                        "Every inputs are 0-1. (i.e. if '50%' is equal to '0.5') \n"
                        + "After finished put all the input, click 'set' button.", 
                "Instruction", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel5MouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton auto;
    private javax.swing.JLabel countLabel;
    private javax.swing.JTextField densityText;
    private javax.swing.JTextField fireprobText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel numTreeLabel;
    private javax.swing.JTextField probBurnText;
    private javax.swing.JButton resetbutt;
    private javax.swing.JComboBox setSize;
    private javax.swing.JButton setbutt;
    private javax.swing.JButton startbutt;
    // End of variables declaration//GEN-END:variables

    /*private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getClass().getResource("icon.png"));
    }*/
}
